use crate::assembly::assembly_result::{AssembledPaths, AssemblyResult};
use crate::assembly::node_datum::NodeDatum;
use crate::detail::hapcmp::HapCompare;
use crate::detail::range::Range;
use crate::detail::util::{all_simple_paths, DError, DResult, HashMap, HashSet};
use crate::io::json::{ParaphaseOutput, ReadAlignmentId, ReadFingerprintMap};

use anyhow::anyhow;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::hash::BuildHasherDefault;

use vstr::{VStr, VString};

use itertools::{intersperse, iproduct, Itertools};
use petgraph::stable_graph::{NodeIndex, StableGraph as PetGraph};
use petgraph::visit::{EdgeRef, IntoEdgeReferences};
use trimothy::TrimSliceMatches;

/**
 * `Graph` class, port of the `Paraphase` equivalent class.
 * It is generated from a set of alignment ids (name + optional alignment number)
 * and associated fingerprints, as generated by alignments and variant site selection.
 *
 * The original implementation uses python structures to store nodes, edges,
 * and provide access to each.
 * We currently use a mix of petgraph and dictionary structures to support graph properties.
 *
 * `ReadAlignmentId` replaces the string names of reads.
 * This is because unlike Paraphase, we want to phase VNTRs, and it's therefore possible to have multiple alignments per read.
 * Most are straight ports, but typed.
 * We describe the exceptions here.
 * 1. For paralog/homolog phasing, there is simply no alignment id associated.
 *    This replaces `{read_name: read_hap}` for reads.
 * 2. The Graph Structure.
 *   In paraphase, it is made up of:
 *     List of edges
 *     List of nodes
 *     next-per-node and previous-per-node
 *     `edge_info`: map from edge to counts of supporting reads.
 *     `edge_per_position`: map from positions to edges
 *
 *  In `paraph-rs`, we use `petgraph` to store most of the data:
 *     We use a directed graph with `NodeType(String, position as u32)` as node type and `Vec<u32>` as edge type.
 *     These `u32`s identify which readalignments support the specific edge.
 *
 *  In addition to the graph structure, we have some helper objects.
 * `read_aln_id_map`: `HashMap` from `ReadAlignmentId` to a numeric id associated with it so that it's easy to pass around an identifier.
 * `node_id_map`: `HashMap` to look up a node's numeric id from the node value.
 *
 * `pos_edge_map` is a straight port of `edge_per_position`.
 * We do not store `edge_info` because its information is stored in `pos_edge_map`.
 *
 * When adding a node, one needs to update `id_node_by_map` to both get the id and see if it was newly inserted.
 *
 */

#[derive(Debug, Clone)]
pub struct GraphError {
    pub msg: String,
}

impl GraphError {
    #[must_use]
    pub fn new(x: impl Into<String>) -> Self {
        Self { msg: x.into() }
    }
}

impl std::error::Error for GraphError {}

impl std::fmt::Display for GraphError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "GraphError{{msg: {}}}", self.msg)
    }
}

/// Class describing nature of the graph at a given position.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum SegmentationClass {
    Unassigned,
    Two, // Unambiguous: only one out edge
    Ten, // Ambiguous: multiple out edges
}

impl SegmentationClass {
    #[must_use]
    pub fn is_assigned(&self) -> bool {
        matches!(self, Self::Two | Self::Ten)
    }
}

pub type NodeType = NodeDatum;
pub type EdgeType = Vec<u32>; // Vector of read ids
pub type IxType = u32;
pub type VGraph = PetGraph<NodeType, EdgeType, petgraph::Directed, IxType>;
/// best match score + vector of matches sharing that score.
pub type MatchingHapSet<'a> = (i32, Vec<VStr<'a>>);

/// Settings for `Graph` haplotype assembler.
/// Most use cases will use default.
///
/// `min_match_count`: Minimum number of fingerprint positions for matching reads against candidate haplotypes. Raising this increases specificity but reduces sensitivity.
/// `min_hap_support`: Minimum number of reads supporting a haplotype for final filtering.
/// `pivot_index`: Used for partitioning the graph based on a pivot position.
///
/// Defaults to `(4, 1, 0)`.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct Settings {
    pub min_match_count: i32, /* Minimum number of fingerprint positions for matching reads against candidate haplotypes. Raising this increases specificity but reduces sensitivity. */
    pub min_hap_support: i32, /* Minimum number of reads supporting a haplotype for final filtering. */
    pub pivot_index: i64,     // Used for partitioning the graph based on a pivot position.
}

impl std::default::Default for Settings {
    fn default() -> Self {
        Self {
            min_hap_support: 4,
            min_match_count: 1,
            pivot_index: -1,
        }
    }
}

impl Settings {
    /// Construct settings from a pivot index, otherwise using defaults of 1 match for partial haplotypes and minimum 4 read support for inclusion.
    #[must_use]
    pub fn from_pivot(pivot_index: Option<i64>) -> Self {
        let pivot_index = pivot_index.unwrap_or(-1);
        log::debug!("Building settings from pivot_index {pivot_index}");
        Self {
            pivot_index,
            ..Default::default()
        }
    }
}

pub type NodeMapType = BTreeMap<NodeDatum, u32>;

/// For ease - tuple. `(from_id, to_id, count)`
pub type WeightedEdge = (u32, u32, u32);

/// `Graph` is the core data structure for haplotype assembly.
/// Using a set of extracted fingerprints, it segments the graph, assembles local regions, and then chains them
/// into a set of assembled haplotypes.
/// 50% unit test coverage currently.
/// Typically created from `ReadFingerprintMap`, a map from `ReadAlignmentId` to `VString`.
/// The `Option<i32>` member for `ReadAlignmentId` allows us to have multiple fingerprints per read. (e.g., Kringle type IV repeat 2 aka KIV2).
#[derive(Debug, Default)]
pub struct Graph {
    pub settings: Settings,
    pub nvar: usize,
    pub reads: ReadFingerprintMap,
    pub reads_original: ReadFingerprintMap,
    pub graph: VGraph,
    read_aln_id_map: BTreeMap<ReadAlignmentId, u32>,
    pub node_id_map: NodeMapType, // Map from NodeDatum (hap, position) to index
    pub pos_edge_map: BTreeMap<usize, Vec<WeightedEdge>>, /* Vector from position to all the edges at that position. */
    pub edge_info: Vec<Vec<u32>>,                         // Vector of vectors of counts.
    pub dnhap: BTreeMap<u32, SegmentationClass>, /* Copy of dnhap from paraphase, except we use Option<i32> instead of i32 with -1 as a special case. */
    pub(crate) node_positions: HashMap<u32, (u32, u32)>,
    total_node_count: usize, /* Total number of nodes. Needed to maintain node numbering while handling deletions. */
}

impl std::ops::Deref for Graph {
    type Target = VGraph;
    fn deref(&self) -> &Self::Target {
        &self.graph
    }
}

impl std::ops::DerefMut for Graph {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.graph
    }
}

const ALPHABET: &[u8] = &[b'0', b'1', b'2', b'3', b'4', b'x', b'A', b'C', b'G', b'T'];

impl std::convert::TryFrom<&ParaphaseOutput> for Graph {
    type Error = GraphError;
    fn try_from(x: &ParaphaseOutput) -> Result<Self, Self::Error> {
        Self::try_from(x.clone())
    }
}

impl std::convert::TryFrom<ParaphaseOutput> for Graph {
    type Error = GraphError;
    fn try_from(x: ParaphaseOutput) -> Result<Self, Self::Error> {
        let pivot_index = x.pivot_index(None);
        Self::try_new(x.read_to_hap, Some(Settings::from_pivot(Some(pivot_index))))
    }
}

/// Stores a view to a read name + align id + an associated path.
/// This lets us return references to the relevant alignment without copying data.
#[derive(Clone, Copy, Hash, Eq, PartialEq)]
pub struct ReadHapPair<'a> {
    pub name: &'a str,
    pub path: &'a VString,
}

impl<'a> std::fmt::Display for ReadHapPair<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}-{}", self.name, self.path)
    }
}

impl<'a> std::fmt::Debug for ReadHapPair<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{self}")
    }
}

/*
/// Metadata for paths. For now it's a count and not used.
#[derive(Default, Clone, Copy, Debug, Hash, Eq, PartialEq, Ord, PartialOrd)]
pub struct AsmDatum {
    pub count: i32,
}

impl AsmDatum {
    pub fn update(&mut self) {
        self.count += 1;
    }
    pub fn consume(&mut self, other: Self) {
        self.count += other.count;
    }
}
*/

/// Maps from hap ids to read alignments (unique and ambiguous), as well as a map from read alignments
/// to potential hap ids.
/// Compared to the python implementation, we use numeric u32 ids for the provided fingerprints instead of a reference to the path itself for lifetime management ease.
#[derive(Clone)]
pub struct ReadHapSupport<'a> {
    pub support_reads: HashMap<u32, Vec<ReadHapPair<'a>>>, /* hap ids and their unique matches. Read alignments here have a unique haplotype match. */
    pub support_reads_nonunique: HashMap<u32, Vec<ReadHapPair<'a>>>, /* hap ids and their non-unique matches. Read alignments here have more than one candidate haplotype/fingerprint. */
    pub supporting_haps_per_read: HashMap<ReadHapPair<'a>, Vec<u32>>,
}

impl<'a> std::fmt::Debug for ReadHapSupport<'a> {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(
            f,
            "Support: {:?}\nAmbiguous Support: {:?}\n: HapsPerRead: {:?}",
            self.support_reads, self.support_reads_nonunique, self.supporting_haps_per_read
        )
    }
}

pub type DBeforeNext<'a> = BTreeMap<VStr<'a>, BTreeSet<VStr<'a>>>;

/// Definition for results after merging positions.
pub type MergePosResult<'a> = (
    BTreeMap<VString, Vec<&'a ReadAlignmentId>>,
    DBeforeNext<'a>,
    DBeforeNext<'a>,
);

/// When we merge subregions, we receive a 4-tuple.
/// bool: assembly success
/// `pos1_haps`: `Vec<VString>` - assembled haps.
/// where `dnext` and `dbefore` has pairs of connected fingerprint substrings.
/// `dnext`, `dbefore`: `BTreeMap<VString, BTreeSet<VString>>`.
pub type SubregionResult = (
    bool,
    Vec<VString>,
    BTreeMap<VString, BTreeSet<VString>>,
    BTreeMap<VString, BTreeSet<VString>>,
);

impl Graph {
    /// Construct a `Graph` from a Map of (read: hap) and optional settings and unwraps.
    ///
    /// For a fallible constructor, use `Graph::try_new`.
    /// If settings is `None`, uses `Settings::default()`
    ///
    /// # Panics
    /// 1. errors on `GraphError` - inconsistent number of variant sites, too few sites.
    #[must_use]
    pub fn new(reads: ReadFingerprintMap, settings: Option<Settings>) -> Self {
        Self::try_new(reads, settings).unwrap_or_else(|e| panic!("Failed to create Graph: {e:?}"))
    }

    /// Construct a `Graph` from a Map of (read: hap) and optional settings.
    /// If settings is `None`, uses `Settings::default()`
    /// # Errors
    /// 1. `GraphError` - inconsistent number of variant sites, too few sites.
    pub fn try_new(
        reads: ReadFingerprintMap,
        settings: Option<Settings>,
    ) -> Result<Self, GraphError> {
        log::trace!("Building from graph from reads {reads:?}");
        let settings = settings.unwrap_or_default();
        let sizes = reads.values().map(|x| x.len()).collect::<BTreeSet<_>>();
        match sizes.len() {
            0 => return Err(GraphError::new(String::from("No input reads to assemble."))),
            1 => {}
            _ => {
                return Err(GraphError::new(format!("Found multiple sizes: {sizes:?}")));
            }
        }
        let nvar = sizes.iter().copied().next().unwrap_or(0);
        if nvar < 1 {
            return Err(GraphError::new(format!("Too few sites: {nvar}")));
        }
        let read_aln_id_map = reads
            .keys()
            .enumerate()
            .map(|(idx, name)| (name.clone(), idx as u32))
            .collect::<BTreeMap<_, _>>();
        let reads_original = reads.clone();
        Ok(Self {
            settings,
            nvar,
            reads,
            reads_original,
            read_aln_id_map,
            graph: VGraph::with_capacity(nvar, nvar * 2),
            ..Default::default()
        })
    }

    /// Checks if the node is made entirely of non-1 or 2.
    /// This means it's not ref or non-ref, so it's a deletion or other special operation.
    #[inline]
    fn node_is_sv(node_id: &NodeDatum) -> bool {
        node_id.hap.iter().all(|x| !matches!(x, b'1' | b'2'))
    }

    /// Compute a map from node ids to node refernces.
    /// This is an implementation detail that should not be needed.
    #[must_use]
    pub(crate) fn get_id_lookup(&self) -> HashMap<u32, &NodeDatum> {
        self.node_id_map
            .iter()
            .map(|(x, y)| (*y, x))
            .collect::<HashMap<u32, &NodeDatum>>()
    }

    /// Remove edges which have low support.
    pub fn prune_edges(&mut self) -> DResult {
        log::debug!("Pruning edges");
        let id_to_node = self
            .get_id_lookup()
            .into_iter()
            .map(|(x, y)| (x, y.to_owned()))
            .collect::<HashMap<_, _>>();
        assert!(!self.pos_edge_map.is_empty());
        let mut tmp_pos_edge = BTreeMap::<usize, Vec<WeightedEdge>>::default();
        std::mem::swap(&mut tmp_pos_edge, &mut self.pos_edge_map);
        let mut edges_to_remove: BTreeMap<usize, Vec<(u32, u32, u32)>> = BTreeMap::new();
        for (pos, edges) in &tmp_pos_edge {
            let num_edges = edges.iter().map(|x| x.2).collect::<Vec<_>>();
            let has_sv = edges
                .iter()
                .flat_map(|x| [x.0, x.1].into_iter())
                .any(|x| Self::node_is_sv(&id_to_node[&x]));
            /*
                has_sv = True in [
                at[0].split("-")[0] not in ["1", "2"]
                or at[1].split("-")[0] not in ["1", "2"]
                for at in self.edge_per_position[pos]
            ]
            */
            let threshold = Self::edge_support_threshold(&num_edges[..]);
            log::trace!(
                "has sv: {has_sv}@pos{pos}. Threshold: {threshold}. num edges: {num_edges:?}"
            );
            for edge in edges.iter() {
                let (from, to, count) = edge;
                let outgoing_from = self
                    .graph
                    .edges_directed(
                        NodeIndex::new(*from as usize),
                        petgraph::Direction::Outgoing,
                    )
                    .count();
                let incoming_to = self
                    .graph
                    .edges_directed(NodeIndex::new(*to as usize), petgraph::Direction::Incoming)
                    .count();
                let nonunique_edges = (outgoing_from > 1) && (incoming_to > 1);
                let fails = nonunique_edges && ((*count <= threshold) || (has_sv && *count == 1));
                if fails {
                    edges_to_remove.entry(*pos).or_default().push(*edge);
                }
            }
        }
        std::mem::swap(&mut tmp_pos_edge, &mut self.pos_edge_map);
        log::trace!("Edges removed: {edges_to_remove:?}");
        // Remove edges + updated pos_edge_map + initialize edge_info (site: number of reads map)
        for (pos, edges) in &edges_to_remove {
            for edge in edges {
                self.rm_edge(*edge)?;
                if let Some(val) = self.pos_edge_map.get_mut(pos) {
                    val.retain(|x| x != edge);
                };
            }
        }

        // Now, update the reads: mark as "x" if edge removed.
        // update_reads in Paraphase.
        let mut read_ids_to_delete = Vec::new();
        for (read_name, read_seq) in &mut self.reads {
            let mut new_seq = read_seq.clone();
            let mut num_found = 0usize;
            let mut total = 0usize;
            for read_idx in (0..(read_seq.len() - 1))
                .filter(|x| read_seq[*x..(*x + 2)].iter().all(Self::is_valid))
            {
                total += 1;
                let from = read_seq[read_idx];
                let to = read_seq[read_idx + 1];
                let from_pos = NodeDatum::from((from, read_idx));
                let to_pos = NodeDatum::from((to, read_idx + 1));
                let from_pos = match self.node_id_map.get(&from_pos) {
                    Some(x) => *x,
                    None => u32::MAX,
                };
                let to_pos = match self.node_id_map.get(&to_pos) {
                    Some(x) => *x,
                    None => u32::MAX,
                };
                let found = self.pos_edge_map[&read_idx]
                    .iter()
                    .any(|x| (x.0, x.1) == (from_pos, to_pos));
                if found {
                    num_found += 1;
                } else {
                    log::trace!("After removing edges, we no longer have one between {from}/{from_pos} and {to}/{to_pos} at site {read_idx}. Old string: {}", VStr::from(&new_seq[read_idx..read_idx + 2]));
                    new_seq[read_idx] = b'x';
                    new_seq[read_idx + 1] = b'x';
                }
            }
            log::trace!("Found {num_found}/{total} edges for {read_name}");
            // If we have at least 2 non-'x' characters, assign new haplotype.
            if bytecount::count(&new_seq, b'x') <= self.nvar - 2 {
                *read_seq = new_seq;
            } else {
                read_ids_to_delete.push(read_name.clone());
            }
        }

        for read_aln_id in read_ids_to_delete {
            assert!(
                self.reads.remove(&read_aln_id).is_some(),
                "Failed to remove read_aln_id: {read_aln_id}"
            );
        }

        self.edge_info = self.make_edge_info();
        log::trace!(
            "Pruned edges; edge info after construction: {:?}",
            self.edge_info
        );
        self.display_state("Pruned edges.");
        Ok(())
    }

    /// Iterate over all nodes.
    /// Unlike the node iteration provided by petgraph, this is aware of deleted nodes.
    pub fn node_iter(&self) -> impl Iterator<Item = &NodeDatum> {
        self.node_id_map.keys().filter(|x| !x.is_del())
    }

    /// Remove an edge from the graph using a `WeightedEdge`, which is numeric ids.
    fn rm_edge(&mut self, edge: WeightedEdge) -> DResult {
        let index = self
            .graph
            .find_edge(
                NodeIndex::new(edge.0 as usize),
                NodeIndex::new(edge.1 as usize),
            )
            .ok_or_else(|| {
                anyhow::anyhow!("Cannot remove edge that does not exist. [graph.find_edge()]")
            })?;
        self.graph.remove_edge(index).ok_or_else(|| {
            anyhow::anyhow!("Cannot remove edge that does not exist [graph.rm_edge(index)]")
        })?;
        Ok(())
    }

    /// Find reads that match given haplotypes and vice versa.
    pub fn match_reads_and_haps<'a, 'b, Iter, T>(
        reads: &'a ReadFingerprintMap,
        haps: Iter,
        min_match: Option<i32>,
    ) -> Result<ReadHapSupport<'a>, DError>
    where
        vstr::VStr<'b>: From<T>,
        Iter: IntoIterator<Item = T>,
    {
        /*
        let read_info_vec = reads
            .iter()
            .map(|(k, v)| ReadHapPair {
                name: &k.read_name[..],
                path: v,
                align_id: k.align_id,
            })
            .collect::<Vec<_>>();
        */
        let haps = haps
            .into_iter()
            .map(VStr::from)
            .map(VString::from)
            .collect::<Vec<_>>();
        let min_match = min_match.unwrap_or(1);
        log::trace!("[match_reads_and_haplotypes] {} reads into {} haps reads: {reads:?} against haps {:?} with min match {min_match}", reads.len(), haps.len(), haps);
        let mut support_reads_nonunique: HashMap<u32, Vec<ReadHapPair>> =
            HashMap::with_capacity_and_hasher(haps.len(), BuildHasherDefault::default());
        let mut support_reads: HashMap<u32, Vec<ReadHapPair>> =
            HashMap::with_capacity_and_hasher(haps.len(), BuildHasherDefault::default());
        for idx in 0..haps.len() {
            support_reads_nonunique.insert(idx as u32, vec![]);
            support_reads.insert(idx as u32, vec![]);
        }
        let mut supporting_haps_per_read: HashMap<ReadHapPair, Vec<u32>> =
            HashMap::with_capacity_and_hasher(reads.len() / 2, Default::default());
        for (fprint, info) in reads.iter().map(|(k, v)| {
            (
                v,
                ReadHapPair {
                    name: &k.read_name[..],
                    path: v,
                },
            )
        }) {
            let mut matching_hapids: Vec<u32> = Vec::new();
            for (hap_id, hap_to_extend) in haps.iter().map(|x| -> VStr<'_> { x.into() }).enumerate()
            {
                let result = HapCompare::from_haps(hap_to_extend, fprint.vstr())?;
                if result.mismatches == 0 && result.matches >= min_match && result.extra >= 0 {
                    let hap_id = hap_id as u32;
                    matching_hapids.push(hap_id);
                    support_reads_nonunique
                        .entry(hap_id)
                        .or_default()
                        .push(info);
                }
            }
            assert!(
                supporting_haps_per_read
                    .insert(info, matching_hapids.clone())
                    .is_none(),
                "Duplicate read id in map... is this possible?"
            );
            if matching_hapids.len() == 1 {
                log::trace!(
                    "Support read for hapid {} matches uniquely {info:?}",
                    matching_hapids[0]
                );
                support_reads
                    .entry(matching_hapids[0])
                    .or_default()
                    .push(info);
                continue;
            }
            for lh_hap_id in matching_hapids.iter().copied() {
                let has_overlap = matching_hapids.iter().copied().any(|rh_hap_id| {
                    rh_hap_id != lh_hap_id && {
                        let compare = HapCompare::from_haps(
                            &haps[lh_hap_id as usize],
                            &haps[rh_hap_id as usize],
                        )
                        .unwrap();
                        std::cmp::max(compare.matches, compare.mismatches) > 0
                    }
                });
                if !has_overlap {
                    support_reads.entry(lh_hap_id).or_default().push(info);
                }
            }
        }
        Ok(ReadHapSupport {
            support_reads,
            support_reads_nonunique,
            supporting_haps_per_read,
        })
    }

    /// Check for possible haps made from missing for later extension.
    fn match_all_reads_and_haps(&mut self) -> DResult {
        for (i, pos, node) in itertools::iproduct!(ALPHABET.iter(), 0..self.nvar)
            .map(|(i, pos)| (i, pos, NodeDatum::from((*i, pos))))
        {
            if self.node_id_map.contains_key(&node) {
                continue;
            }
            let mut hap = VString::from(vec![b'x'; pos]);
            hap.reserve_exact(self.nvar);
            hap.push(*i);
            hap.resize(self.nvar, b'x');
            let read_support = Self::match_reads_and_haps(
                &self.reads_original,
                &[hap],
                Some(self.settings.min_match_count),
            )?;
            // We are annotate by hapids instead of passing around the haps.
            // That means that [hap] has only one hapid: 0.
            if read_support
                .support_reads
                .get(&0)
                .map_or(0, std::vec::Vec::len)
                > 1
            {
                let (node_id, node_was_new) =
                    Self::id_node_by_map(&mut self.node_id_map, &node, &mut self.total_node_count);
                debug_assert!(node_was_new, "Node should have been new at construction.");
                let graph_id = self.graph.add_node(node);
                debug_assert_eq!(graph_id.index() as u32, node_id);
            }
        }

        Ok(())
    }

    /// For debug purposes, print nodes/edges.
    fn display_state(&self, msg: impl Into<String>) {
        let msg = msg.into();
        log::debug!(
            "{msg}. Nodes: {:?}. Edges: {:?}",
            self.formatted_nodes(),
            self.formatted_edges()
        );
    }

    /// Initialization:
    /// Set up graph, prune edges, and match reads and haplotypes.
    /// This is one of two major components: `init`, and `run_asm`.
    /// `init` sets up the graph and annotates.
    pub fn init(&mut self) -> DResult {
        // init + prune both correspond to self.get_edges and self.update_reads in paraphase-py
        // We do both together because it's easier.
        self.init_edges();
        self.display_state("[init] Edges initialized.");

        self.prune_edges()?;
        self.display_state("[init] Edges pruned.");

        // Next, associate reads and haplotypes.
        self.match_all_reads_and_haps()?;

        self.display_state("[init] reads matched to haps.");

        Ok(())
    }

    /// Performs assembly.
    /// Assumes that `init()` has been run successfully.
    ///
    /// Assembles haplotypes, identifies possible copy numbers, extends candidates,
    /// and selects final haplotypes to assign.
    ///
    /// This is one of two major components: `init`, and `run_asm`.
    /// `run_asm` assembles the graph.
    pub fn run_asm(&mut self) -> Result<AssemblyResult, DError> {
        // Assemble
        let init_haps = self.assemble_haps()?;
        log::debug!("Initially-assembled haps: {init_haps:?}");
        let hap_len = init_haps.iter().next().map_or(0, |x| x.len());
        if hap_len != self.nvar {
            Err(anyhow!(
                "Assembly failed because haplotypes have length {0} but expected {1}",
                hap_len,
                self.nvar
            ))?;
        }
        // Filter
        let final_haps = self.filter_low_support_haps(&init_haps)?;
        log::debug!("Filtered and assembled haps: {final_haps:?}");
        self.display_state("State after filtering");
        // Hap sets
        let (highest_cn, main_haps_candidates) = self.get_highest_cn(final_haps.iter())?;
        log::debug!(
            "Highest copy number possible: {highest_cn}. {} haplotype set candidates, {main_haps_candidates:?}",
            main_haps_candidates.len()
        );
        // main haps candidates: Vec<Vec<VStr>>
        // Extend haps
        let extended_main_hap_candidates = main_haps_candidates
            .iter()
            .map(|x| {
                let extended = self.extend_pivot_blocks(x.iter());
                log::debug!("Extended block {x:?} to {extended:?}");
                extended
            })
            .collect::<Vec<_>>();
        log::debug!("Extended candidates: {extended_main_hap_candidates:?}");
        let main_haps = self.select_main_haps(&final_haps, extended_main_hap_candidates);
        log::debug!("main haps: {main_haps:?}");

        Ok(AssemblyResult {
            main_haps,
            final_haps,
            highest_cn,
        })
    }

    /// Choose the haplotypes with the best support.
    #[must_use]
    pub fn select_main_haps(
        &self,
        final_haps: &AssembledPaths,
        mut candidates: Vec<AssembledPaths>,
    ) -> AssembledPaths {
        log::debug!(
            "Choosing best paths in {final_haps:?} using candidates for pivoting {candidates:?}. pivot: {}", self.settings.pivot_index
        );
        let ret = if self.settings.pivot_index < 0 {
            assert!(!candidates.is_empty(), "No extended candidates");
            std::mem::take(&mut candidates[0])
            //candidates
            //    .first_mut()
            //    .map_or_else(|| final_haps.clone(), std::mem::take)
        } else {
            let best_scores = candidates
                .into_iter()
                .map(|cand| {
                    log::trace!(
                        "pivot ones: {:?} for cand {cand:?}. Pivot index is {}",
                        cand.clone()
                            .into_inner()
                            .into_iter()
                            .filter(|hap| hap[self.settings.pivot_index as usize] != b'x')
                            .collect::<Vec<_>>(),
                        self.settings.pivot_index
                    );
                    let pivot_ones = cand
                        .into_inner()
                        .into_iter()
                        .filter(|hap| hap[self.settings.pivot_index as usize] != b'x')
                        .collect::<Vec<_>>();
                    let nhap = pivot_ones.len();
                    let total_length = pivot_ones
                        .iter()
                        .map(|seq| seq.trim_matches(|x| x == b'x').len())
                        .sum::<usize>();
                    let num_matching_fhaps = final_haps
                        .iter()
                        .filter(|fhap| {
                            pivot_ones
                                .iter()
                                .map(|x| {
                                    HapCompare::from_haps(fhap.vstr(), x.vstr())
                                        .expect("Failed to compare haps of different lengths")
                                        .mismatches
                                })
                                .min()
                                .unwrap_or(1)
                                == 0
                        })
                        .count();
                    ((nhap, num_matching_fhaps, total_length), pivot_ones)
                })
                .sorted_by_key(|x| std::cmp::Reverse(x.0))
                .collect::<Vec<_>>();
            log::trace!("best scores, sorted : {best_scores:?}");
            let best = best_scores.first().expect("No candidates...").0;
            AssembledPaths::from_seqs(
                // If these all tie, tie-break by the one with the fewest haplotypes because it is the simplest
                // paraphase just takes the first one after sorting, so it tie-breaks based on the pivot_ones comparator.
                best_scores
                    .into_iter()
                    .filter_map(|x| if x.0 == best { Some(x.1) } else { None })
                    .min_by_key(std::vec::Vec::len)
                    .expect("Needed at least one option"),
            )
        };
        if ret.is_empty() {
            final_haps.clone()
        } else {
            ret
        }
    }

    /// Run full construction: initialize graph and run assembly.
    pub fn construct(&mut self) -> Result<AssemblyResult, DError> {
        self.init()?;
        self.run_asm()
    }

    /// Break the graph up into easier/harder segments to assemble separately.
    /// Returns `Result<Map<Range, Option<i32>>`, where `Option<i32>` is the category for that range,
    /// , `Range<u32>` is the end-inclusive/`x..=y` range for positions for each segment.
    /// By using a `BTreeMap`, these are ordered by position.
    pub fn segment_graph(&self) -> Result<BTreeMap<Range<u32>, SegmentationClass>, DError> {
        use SegmentationClass::{Ten, Two};
        log::trace!("dnhap before segmentation: {:?}", self.dnhap);
        let mut dnhap = self.dnhap.clone();
        let keys = dnhap.keys().copied().collect::<Vec<u32>>();
        let values = dnhap.values().copied().collect::<Vec<_>>();
        // const BOX: &[Option<i32>] = &[Ten, Two, Two, Ten];
        // 10, 2, 2, 10 is like a particle-in-a-box.
        assert_eq!(values.len(), keys.len());
        values
            .windows(3)
            .zip(keys.iter().copied().skip(1))
            .enumerate()
            .for_each(|(window_index, (v, k))| {
                if v == [Ten, Two, Ten] {
                    // k_window[1] is the item in the middle of this window; we need v[-1] and v[1] to check for 10-2-10, but k[0] is the corresponding keys.
                    log::trace!("10-2-10 at window idx {window_index}/centroid {} which means the range is {window_index}..={}, setting to Ten. k: {k}", window_index + 1, window_index + 2);
                    dnhap.insert(k, Ten);
                }
            });
        assert!(keys.windows(2).all(|x| x[1] >= x[0]));
        log::trace!("After filling local dnhap, the value is {dnhap:?}");

        let mut segment_pos = 0u32;
        Ok(dnhap
            .iter()
            .group_by(|x| *x.1)
            .into_iter()
            .map(|(key, group)| {
                let group_len = group.count() as u32;
                let segment_end = segment_pos + group_len;
                let range = Range::new(segment_pos, segment_end - 1);
                segment_pos = segment_end;
                (range, key)
            })
            .collect::<BTreeMap<_, _>>())
    }

    /// Generate potential paths between nodes at positions.
    pub fn path(&self, ivl: Range<u32>) -> Result<AssembledPaths, DError> {
        let mut ret = AssembledPaths::new();
        let sources = self.pos_edge_map[&(ivl.start as usize)]
            .iter()
            .filter(|x| self.find_edge(x.0.into(), x.1.into()).is_some()) // Skip edges which have been deleted.
            .map(|x| x.0)
            .collect::<BTreeSet<_>>();
        let targets = self.pos_edge_map[&((ivl.end - 1) as usize)]
            .iter()
            .filter(|x| self.find_edge(x.0.into(), x.1.into()).is_some()) // Skip edges which have been deleted.
            .map(|x| x.1)
            .collect::<BTreeSet<_>>();
        for (source, target) in
            itertools::iproduct!(sources.iter().copied(), targets.iter().copied())
        {
            all_simple_paths(
                &self.graph,
                source.into(),
                target.into(),
                0,
                Some(ivl.len()),
            )
            .into_iter()
            .map(|path| {
                intersperse(
                    path.into_iter().map(|x| {
                        self.graph
                            .node_weight(x)
                            .expect("Missing node")
                            .hap
                            .to_string()
                    }),
                    String::default(),
                )
                .collect::<VString>()
            })
            .for_each(|hap| {
                ret.insert(hap);
            });
        }
        Ok(ret)
    }

    /// Merge nodes in nstart..=nend.
    pub fn merge_where_possible(&mut self, mut nstart: u32, nend: u32) -> DResult {
        log::trace!(
            "before merge_where_possible: {:?}. Formatted nodes {:?}. Formatted pos_edge_map: {:?}",
            self.pos_edge_map,
            self.formatted_nodes(),
            self.formatted_edges(),
        );
        let mut inum = 1usize;
        while nstart < nend - 1 {
            let istr = format!("[merge_where_possible@{inum}");
            log::trace!(
                "{istr} Edges before: {:?}. Nodes before subregion assembly: {:?}",
                self.formatted_edges(),
                self.formatted_nodes()
            );
            let (success, final_haps, _dnext, _dbefore) =
                self.subregion_assembly(nstart, nend, false)?;
            log::trace!("{istr} Subregion assembly result scanning for {nstart}..={nend}: {success}, {final_haps:?}");
            let current_haps = self.get_hap_by_pos(nstart).collect::<Vec<_>>();
            log::trace!("{istr} for {nstart}..={nend}, pos haps are {current_haps:?}. dnext {_dnext:?}, dbefore {_dbefore:?}");
            let final_len = final_haps[0].len();
            let pos = nstart + (final_len as u32);
            let block_ending_pos = self
                .get_previous_pos(pos)
                .expect("Expected a previous position.");
            let current_len = current_haps[0].len();
            if current_len != final_len {
                log::trace!("{istr} rm_add_edges between {nstart} and {block_ending_pos}");
                self.rm_add_edges(nstart, block_ending_pos, final_haps.into_iter())?;
            } else {
                log::trace!("{istr} lengths match, no rm_add_edges. current haps len {current_len}, final haps len {final_len}");
            }
            nstart = pos;
            if success {
                log::trace!("{istr} Finished assembling region in {inum} iterations.");
                break;
            }
            inum += 1;
        }
        Ok(())
    }

    /// Merge the simple edges for segments that don't need additional assembly.
    pub fn merge_simple_edges_from_segments(
        &mut self,
        segments: &BTreeMap<Range<u32>, SegmentationClass>,
    ) -> DResult {
        let num_segments = segments.len();
        // Merge simple edges
        for (segment_id, (segment, _height)) in segments
            .iter()
            .enumerate()
            .filter(|(_id, (_segment, height))| **height == SegmentationClass::Two)
        {
            // Adjust start/end
            let mut segment_start = segment.start;
            let mut segment_end = segment.end;
            if segment_id > 0 && segment_id != (num_segments - 1) {
                // If not first or last segment, increment segment_start
                segment_start += 1;
            }
            if segment_end == (self.nvar - 2) as u32 {
                segment_end += 1;
            }
            if segment_end > segment_start {
                self.merge_edges_simple(segment_start, segment_end)?;
            }
        }
        Ok(())
    }

    pub fn merge_complex_regions(
        &mut self,
        segments: BTreeMap<Range<u32>, SegmentationClass>,
    ) -> DResult {
        for (segment, _height) in segments.into_iter().filter(|(segment, height)| {
            *height == SegmentationClass::Ten && segment.end >= segment.start
        }) {
            self.merge_edges(segment.start, segment.end + 1)?;
        }
        Ok(())
    }

    pub fn assemble_haps(&mut self) -> Result<AssembledPaths, DError> {
        self.summarize_edges()?;
        let segments = self.segment_graph()?;
        log::trace!(
            "dnhap after segmentation: {:?}. Segments: {segments:?}. Pos edge map: {:?}. Formatted nodes: {:?}",
            self.dnhap,
            self.pos_edge_map,
            self.formatted_nodes()
        );
        assert!(
            !segments.is_empty(),
            "edges: {:?}. inputs {:?}",
            self.pos_edge_map,
            self.reads
        );
        if segments.len() == 1 && *segments.values().next().unwrap() == SegmentationClass::Two {
            let ivl = segments.keys().next().unwrap();
            return self.path(Range::<u32>::new(ivl.start, ivl.end + 1));
        }

        self.merge_simple_edges_from_segments(&segments)?;
        log::trace!(
            "pos edge map after simple edge merging: {:?}. Formatted nodes {:?}. Formatted edges: {:?}",
            self.pos_edge_map,
            self.formatted_nodes(),
            self.formatted_edges(),
        );
        self.merge_complex_regions(segments)?;
        log::trace!(
            "pos edge map after complex edge merging: {:?}. Formatted nodes {:?}. Formatted pos_edge_map: {:?}",
                self.pos_edge_map, self.formatted_nodes(), self.formatted_edges(),
        );
        // Then, scan whole graph and merge where possible.

        let (nstart, nend) = self.get_nstart_nend().expect("No nodes in graph?");
        if nstart == nend {
            log::trace!("nstart == nend, no need to merge, {nstart}, {nend}");
            let candidates_to_return = AssembledPaths::from_seqs(self.node_iter().map(|x| &x.hap));
            // check that the candidates are the correct length
            if !candidates_to_return.is_empty()
                && self.nvar == candidates_to_return.first().unwrap().len()
            {
                return Ok(candidates_to_return);
            } else {
                return Ok(AssembledPaths::new());
            }
        }
        log::trace!("nstart = {nstart}, nend = {nend}");
        self.merge_where_possible(nstart, nend)?;

        log::trace!(
            "after merge_where_possible: {:?}. Formatted nodes {:?}. Formatted pos_edge_map: {:?}",
            self.pos_edge_map,
            self.formatted_nodes(),
            self.formatted_edges(),
        );

        // And finish complete merge
        self.merge_blocks_by_size()?;
        log::trace!(
            "after merge_blocks_by_size: {:?}. Formatted nodes {:?}. Formatted pos_edge_map: {:?}",
            self.pos_edge_map,
            self.formatted_nodes(),
            self.formatted_edges(),
        );

        let (nstart, nend) = self.get_nstart_nend().expect("Nodes expected in graph");
        Ok(if nstart == nend {
            log::debug!(
            "final subregion_assembly but nstart == nend: {:?}. Formatted nodes {:?}. Formatted pos_edge_map: {:?}. haps: {:?}",
                self.pos_edge_map, self.formatted_nodes(), self.formatted_edges(), self.node_iter().map(|x| &x.hap[..]).collect::<Vec<_>>());
            AssembledPaths::from_seqs(self.node_iter().map(|x| x.hap.clone()))
        } else {
            log::debug!(
            "before final subregion_assembly: {:?}. Formatted nodes {:?}. Formatted pos_edge_map: {:?}.",
                self.pos_edge_map, self.formatted_nodes(), self.formatted_edges());
            let (_success, haps, _x, _y) = self.subregion_assembly(nstart, nend, true)?;
            log::debug!(
            "after final subregion_assembly: {:?}. Formatted nodes {:?}. Formatted pos_edge_map: {:?}. haps: {haps:?}",
                self.pos_edge_map, self.formatted_nodes(), self.formatted_edges(),
        );
            AssembledPaths::from_seqs(haps)
        })
    }

    /// Find the highest/lowest positions corresponding to current nodes.
    #[must_use]
    pub fn get_nstart_nend(&self) -> Option<(u32, u32)> {
        let mut ret = (u32::MAX, 0);
        for node in self.node_iter() {
            ret.0 = std::cmp::min(ret.0, node.pos);
            ret.1 = std::cmp::max(ret.1, node.pos);
        }
        if ret.0 == u32::MAX {
            None
        } else {
            Some(ret)
        }
    }

    /// Given a pair of (position, hap) pairs in a dictionary, merge the relevant positions.
    /// Returns `sub_hap_support`, dnext, dbefore.
    ///
    /// `sub_hap_support` - dict of (merged haps):(supporting reads)
    /// dnext - dict of (hap1):(set of potential linking hap2s downstream)
    /// dbefore - dict of (hap1):(set of potential linking hap2s upstream)
    pub fn merge_two_pos<'a>(
        &'a self,
        new_nodes: &'a BTreeMap<u32, BTreeSet<VStr<'_>>>,
    ) -> Result<MergePosResult<'a>, DError> {
        let mut sub_hap_support: BTreeMap<VString, Vec<&ReadAlignmentId>> = BTreeMap::new();
        let mut dnext: BTreeMap<VStr, BTreeSet<VStr>> = BTreeMap::new();
        let mut dbefore: BTreeMap<VStr, BTreeSet<VStr>> = BTreeMap::new();
        log::trace!("new_nodes: {new_nodes:?}");
        for (read, fingerprint) in &self.reads {
            let hits = new_nodes
                .keys()
                .map(|x| {
                    let (hap, matches) =
                        Self::get_matching_hap(new_nodes, *x, fingerprint.vstr()).ok()?; // WARNING: This filters out different lengths.
                    matches.map(|matches| (hap, matches))
                })
                .collect::<Vec<_>>();
            if hits.iter().any(Option::is_none) {
                continue;
            }
            let hits = hits
                .into_iter()
                .map(std::option::Option::unwrap)
                .collect::<Vec<_>>();
            /*
            if hits.iter().any(|x| x.is_none()) {
                continue;
            }
            let hits = hits.into_iter().flatten().collect::<Vec<_>>();
            */
            let mut num_matches = hits.iter().map(|(_hap, matches)| matches.1.len());
            if let (Some(1), Some(1)) = (num_matches.next(), num_matches.next()) {
                let mut joined = VString::from(&hits[0].1 .1[0][..]);
                joined.extend_from_slice(&hits[1].1 .1[0][..]);
                sub_hap_support.entry(joined).or_default().push(read);
            }
            log::trace!(
                "hits (a): {:?}. hits (b): {:?}.",
                hits[0].1 .1,
                hits[1].1 .1
            );
            for (a, b) in iproduct!(hits[0].1 .1.iter(), hits[1].1 .1.iter()) {
                dnext.entry(*a).or_default().insert(*b);
                dbefore.entry(*b).or_default().insert(*a);
            }
        }
        Ok((sub_hap_support, dnext, dbefore))
    }

    /// Merge edges by performing subregion assembly from first..=last
    /// and updates the graph if necessary.
    pub fn merge_edges(&mut self, first: u32, last: u32) -> DResult {
        let (success, new_haps, _, _) =
            self.subregion_assembly(first, last, /* allow_w= */ false)?;
        if success {
            log::trace!("Now removing edges for {first}..={last} because success with new haps {new_haps:?}");
            self.rm_add_edges(first, last, new_haps.into_iter())?;
        }

        Ok(())
    }

    /// Handle merging in simple portions of the graph.
    fn merge_edges_simple(&mut self, start: u32, end: u32) -> DResult {
        log::trace!(
            "Merging edges from start to end {start} and {end}. pos edge map before: {:?}",
            self.pos_edge_map
        );
        let path = self.path(Range::<u32>::new(start, end))?;
        self.rm_add_edges(start, end, path.iter().map(|x| x.vstr()))?;
        log::trace!(
            "Merged edges from start to end {start} and {end}. pos edge map now: {:?}",
            self.pos_edge_map
        );
        Ok(())
    }

    /// Yield token strings at position.
    /// Could be faster - we just enumerate all nodes and filter for pos currently.
    /// We should be able to use a `BTree` query to do this in linearithmic.
    pub fn get_hap_by_pos(&self, pos: u32) -> impl Iterator<Item = VStr<'_>> {
        self.node_id_map
            .keys()
            .filter(move |x| !x.is_del() && x.pos == pos)
            .map(|x| x.hap.vstr())
    }

    /// Removes a node by nodeindex from `node_positions`,
    /// sets to node in the graph to deleted, and updates the `node_id_map` with the new weight (which includes deletion).
    /// That means that the old node is no longer present in that map.
    pub(crate) fn fully_remove_node(&mut self, node: NodeIndex) {
        log::trace!("Removing node {}", node.index());
        self.node_positions.remove(&(node.index() as u32));
        let mut weight = if let Some(weight) = self.node_weight_mut(node) {
            let weight_copy = weight.clone();
            assert!(!weight.is_del());
            weight.set_is_del();
            weight_copy
        } else {
            panic!("weight should have been in map for node {node:?}");
        };
        let id = self.node_id_map.remove(&weight).expect("id was not in map");
        weight.set_is_del(); // Set to is deleted
        self.node_id_map.insert(weight, id); // Add back in, but deleted.
    }

    /// Find the next position after `<pos>`
    /// Skip deleted nodes and find the first node that is relevant.
    /// We query the btree for the position in question and walk to the next one to account for arbitary strings in tie-breaking.
    #[must_use]
    pub fn get_next_pos(&self, pos: u32) -> Option<u32> {
        let lower_bound = NodeDatum::new(VString::from("\x7f\x7f\x7f\x7f\x7f\x7f\x7f\x7f"), pos);
        let positions = self.node_id_map.range((
            std::ops::Bound::Excluded(lower_bound),
            std::ops::Bound::Unbounded,
        ));
        positions
            .filter(|x| !x.0.is_del())
            .find(|x| x.0.pos > pos)
            .map(|x| x.0.pos)
    }

    /// Find the first position before `<pos>`
    /// Skip deleted nodes and find the first node that is relevant.
    #[must_use]
    pub fn get_previous_pos(&self, pos: u32) -> Option<u32> {
        let positions = self.node_id_map.range((
            std::ops::Bound::Unbounded,
            std::ops::Bound::Excluded(NodeDatum::from((0u8, pos))),
        ));
        positions.rev().find(|x| !x.0.is_del()).map(|x| x.0.pos)
    }

    /// For the range pos1..=pos2 and given a token path, we remove the edges between and reconstruct the local graph using the given path.
    pub(crate) fn rm_add_edges<T: std::convert::Into<VString>>(
        &mut self,
        pos1: u32,
        pos2: u32,
        path: impl IntoIterator<Item = T>,
    ) -> DResult {
        log::trace!(
            "edge_per_position before adding connecting edges for range {pos1}..={pos2}: {:?}",
            self.pos_edge_map
        );
        let old_edges = self.pos_edge_map.clone();
        let prev = self.get_previous_pos(pos1);
        let start = prev.unwrap_or(0);
        let pos_edge_map_len = self.pos_edge_map.len();
        for idx in (start as usize..=pos2 as usize).filter(|x| *x < pos_edge_map_len) {
            if self.pos_edge_map.contains_key(&idx) {
                let edges_to_remove = self.pos_edge_map[&idx].clone();
                for edge in edges_to_remove {
                    self.rm_edge(edge)?;
                }
                self.pos_edge_map.retain(|k, _| *k != idx as usize);
            }
        }
        log::trace!(
            "Current pos edge map after removing: {:?}",
            self.pos_edge_map
        );
        // If the precedent position is not None, remove it from pos_edge_map as well.
        // Because the code uses .pop(x, None), it does not error on missing.
        if let Some(pos) = prev {
            self.pos_edge_map.retain(|k, _| *k != pos as usize);
            //if let Some(v) = self.pos_edge_map.get_mut(pos as usize) {
            //    v.clear();
            //}
        }
        let contain_range = pos1..=pos2;
        let nodes_to_remove = self
            .node_iter()
            .filter(|x| contain_range.contains(&x.pos))
            .map(|x| self.id_node_const(x).expect("node not found in map"))
            .map(NodeIndex::from)
            .collect::<Vec<_>>();
        for node in nodes_to_remove {
            self.fully_remove_node(node);
        }
        let mut id_lookup = self
            .get_id_lookup()
            .into_iter()
            .map(|(x, y)| (x, y.clone()))
            .collect::<HashMap<_, _>>();

        // Now add in new edges
        let path = path
            .into_iter()
            .map(std::convert::Into::into)
            .collect::<Vec<_>>();
        let npaths = path.len();
        // for i, new_hap in enumerate(new_haps):
        for (i, hap) in path.iter().enumerate() {
            let i = i as u32;
            let node = NodeDatum::new(hap.clone(), pos1);
            let (node_id, was_new) = self.fully_add_node(node.clone());
            log::trace!("Node was {}new", if was_new { "" } else { "not " });
            id_lookup.insert(
                node_id,
                self.node_weight(node_id.into())
                    .expect("Missing node we just added.")
                    .clone(),
            );
            assert!(was_new);
            self.node_positions.insert(
                node_id,
                (
                    pos1 * 1000,
                    if npaths > 2 { i * 5 + 10 } else { (i + 1) * 10 },
                ),
            );
            let maybe_add_edge = |pos_edge_map: &mut BTreeMap<usize, Vec<WeightedEdge>>,
                                  pos: usize,
                                  node1: u32,
                                  node2: u32| {
                pos_edge_map.entry(pos).or_default();
                if let Some(pos_edges) = pos_edge_map.get_mut(&pos) {
                    if !pos_edges.iter().any(|x| (x.0, x.1) == (node1, node2)) {
                        pos_edges.push((node1, node2, 0));
                    }
                }
            };
            if let Some(old) = old_edges.get(&(pos2 as usize)) {
                for (from, to, _) in old {
                    let from_node = id_lookup.get(from).expect("Node missing from id_lookup");
                    if *hap.last().unwrap() != from_node.hap[0] {
                        continue;
                    }

                    let to = *to;
                    self.add_edge(node_id.into(), to.into(), vec![]);
                    let to_weight = self.node_weight(to.into()).expect("Missing node");
                    log::trace!("Added edge from {node_id}/{node:?} to {to}/{to_weight:?} at position {pos1}. Current pos edge map {:?}", self.pos_edge_map);
                    maybe_add_edge(&mut self.pos_edge_map, pos1 as usize, node_id, to);
                }
            }
            if let Some((prev_pos, edges)) = prev
                .map(|x| x as usize)
                .and_then(|x| old_edges.get(&x).map(|edges| (x, edges)))
            {
                edges.iter().copied().for_each(|(node1, node2, _count)| {
                    let node2_node = id_lookup.get(&node2).expect("Node missing node1 id_lookup");
                    if hap[0] == node2_node[0] {
                        // new_hap[0] == node2[0]:
                        self.add_edge(node1.into(), node_id.into(), vec![]); // self.edge_per_position.setdefault(prev_pos, [])
                                                                                /* don't need to do anything, the array is always defined. */ // self.edge_per_position.setdefault(prev_pos, [])
                        log::trace!("Added edge from {node1}/{:?} to new node {node_id}/{node:?} at position {prev_pos}. Current pos edge map {:?}", self.node_weight(node1.into()).unwrap(), self.pos_edge_map);
                        maybe_add_edge(&mut self.pos_edge_map, prev_pos, node1, node_id);
                    }
                });
            }
        }
        log::trace!(
            "edge_per_position after adding connecting edges for range {pos1}..={pos2}: {:?}",
            self.pos_edge_map
        );
        Ok(())
    }

    /// Add the node to all structures - the graph structure, `node_id_map`, and related.
    /// This is the only add node function you should be using.
    /// Returns (`node_id`, `was_new`) when adding.
    /// If it was not new, the original id is returned.
    #[must_use]
    pub fn fully_add_node(&mut self, datum: NodeDatum) -> (u32, bool) {
        let mut total_node_count = self.total_node_count;
        let (idx, was_new) = self.fetch_add_node(&datum, Some(&mut total_node_count));
        self.total_node_count = total_node_count;
        log::trace!("Adding node {datum:?}. Has ID {idx} and was it new? {was_new}");
        if was_new {
            log::trace!("Node  {datum:?} was new. Assigned id: {idx}. Graph has {} nodes, node_id_map has {}", self.graph.node_count(), self.node_id_map.len());
            let graph_idx = self.add_node(datum).index() as u32;
            assert_eq!(graph_idx, idx);
        }
        (idx, was_new)
    }

    /// Adds the node to the map if not present. Also manages the number of nodes, outside of the structure for mutability.
    /// This function is expected to only be used by maintainers.
    #[must_use]
    pub fn fetch_add_node(
        &mut self,
        datum: &NodeDatum,
        num_nodes: Option<&mut usize>,
    ) -> (u32, bool) {
        if let Some(num_nodes) = num_nodes {
            Self::id_node_by_map(&mut self.node_id_map, datum, num_nodes)
        } else {
            let mut num_nodes = self.total_node_count;
            let res = Self::id_node_by_map(&mut self.node_id_map, datum, &mut num_nodes);
            self.total_node_count = num_nodes;
            res
        }
    }

    /// Id a node if present, but do not add.
    #[must_use]
    fn id_node_const(&self, datum: &NodeDatum) -> Option<u32> {
        self.node_id_map.get(datum).copied()
    }

    /// Id a node using a non-member map.
    /// This lets us have another mutable borrow on the Graph object.
    #[must_use]
    fn id_node_by_map(
        map: &mut NodeMapType,
        datum: &NodeDatum,
        num_nodes: &mut usize,
    ) -> (u32, bool) {
        match map.get(datum) {
            Some(x) => {
                log::trace!("Found node: {datum:?} at id {x}");
                (*x, false)
            }
            None => {
                let id = *num_nodes as u32;
                *num_nodes += 1;
                log::trace!(
                    "Did not find node: {datum:?} has new id {id}. New number of nodes: {id}"
                );
                map.insert(datum.clone(), id);
                (id, true)
            }
        }
    }

    /// Convert a `read_aln_id` into a numeric id.
    #[must_use]
    pub fn read_aln_id(&self, name: &ReadAlignmentId) -> Option<u32> {
        self.read_aln_id_map.get(name).copied()
    }

    #[inline]
    fn is_valid(x: &u8) -> bool {
        *x != b'x' // May extend in the future
    }

    /// Cound how many tokens are valid.
    #[must_use]
    fn count_valid(hap: &[u8]) -> usize {
        hap.iter().copied().filter(Self::is_valid).count()
    }

    /// Initialize the graph.
    pub fn init_edges(&mut self) {
        let mut node_id_map = NodeMapType::new();
        std::mem::swap(&mut node_id_map, &mut self.node_id_map); // Ownership hack: move node_id_map out of struct, modify, put back.
        log::trace!("{} reads", self.reads.len());
        let mut total_node_count = self.total_node_count;
        for (read_aln_id, hap) in self.reads.iter().filter(|(_name, hap)| {
            let num_valid = Self::count_valid(&hap[..]);
            assert_eq!(hap.len(), self.nvar);
            num_valid > 0
        }) {
            let read_name = &read_aln_id.read_name[..];
            let read_id = self.read_aln_id(read_aln_id).expect("Missing read name");
            // Skip pairs of adjacent variant positions which have either base as invalid.
            log::trace!("{read_name}:{hap} for {read_id}");
            for (window_index, window) in hap
                .windows(2)
                .enumerate()
                .filter(|x| x.1.iter().all(Self::is_valid))
            {
                let (from, to): (u8, u8) = window.iter().copied().next_tuple().unwrap();
                let from_pos = NodeDatum::from((from, window_index));
                let to_pos = NodeDatum::from((to, window_index + 1));
                let (from_id, from_was_new) =
                    Self::id_node_by_map(&mut node_id_map, &from_pos, &mut total_node_count);
                if from_was_new {
                    let graph_id = self.graph.add_node(from_pos).index() as u32;
                    assert_eq!(from_id, graph_id);
                }
                let (to_id, to_was_new) =
                    Self::id_node_by_map(&mut node_id_map, &to_pos, &mut total_node_count);
                if to_was_new {
                    let graph_id = self.graph.add_node(to_pos);
                    assert_eq!(to_id as usize, graph_id.index());
                }
                let edge_idx = if let Some(e) = self.graph.find_edge(from_id.into(), to_id.into()) {
                    self.graph.edge_weight_mut(e).unwrap().push(read_id);
                    e
                } else {
                    self.graph
                        .add_edge(from_id.into(), to_id.into(), vec![read_id])
                };
                log::trace!(
                    "from {}@{from_id}, to {}@{to_id} are assigned edge {edge_idx:?}",
                    from as char,
                    to as char
                );
            }
        }
        std::mem::swap(&mut node_id_map, &mut self.node_id_map);
        std::mem::swap(&mut total_node_count, &mut self.total_node_count);
        let id_to_node = self.get_id_lookup();
        let mut pos_edge_map: BTreeMap<usize, Vec<(u32, u32, u32)>> = BTreeMap::new();
        for i in 0..(self.nvar - 1) {
            pos_edge_map.insert(i, vec![]);
        }
        let mut edge_info: Vec<Vec<u32>> = vec![vec![]; self.nvar - 1];
        for edge in self.graph.edge_references() {
            let source = edge.source();
            let target = edge.target();
            let weight = edge.weight().len() as u32;
            let v = (source.index() as u32, target.index() as u32, weight);
            let position_index = id_to_node
                .get(&(source.index() as u32))
                .expect("error building graph")
                .pos as usize;
            pos_edge_map.entry(position_index).or_default().push(v);
            edge_info[position_index].push(weight);
        }
        self.pos_edge_map = pos_edge_map;
        self.edge_info = edge_info;
    }

    #[must_use]
    pub fn make_edge_info(&self) -> Vec<Vec<u32>> {
        let id_to_node = self
            .get_id_lookup()
            .into_iter()
            .map(|(x, y)| (x, y.to_owned()))
            .collect::<HashMap<_, _>>();
        let mut edge_info: Vec<Vec<u32>> = vec![vec![]; self.nvar - 1];
        for edge in self.graph.edge_references() {
            let source = edge.source().index() as u32;
            let weight = edge.weight().len() as u32;
            let position_index = id_to_node.get(&source).expect("error edge info").pos as usize;
            edge_info[position_index].push(weight);
        }
        edge_info
    }

    /// Check the number of different edges starting at each position.
    pub fn summarize_edges(&mut self) -> DResult {
        let mut site1 = HashSet::default();
        let mut site2 = HashSet::default();
        let mut expected_site1 = HashSet::default();
        let mut expected_site2 = HashSet::default();
        for (idx, edges) in &self.pos_edge_map {
            let idx = *idx as u32;
            let nhap: SegmentationClass = if edges.iter().map(|x| x.2).max().unwrap_or(1) > 2
                && edges.iter().map(|x| x.2).min().unwrap_or(1) >= 2
            {
                let mut dlinks: HashMap<u32, BTreeSet<u32>> = HashMap::default(); // Map from node id to set of other node ids
                for x in [
                    &mut site1,
                    &mut site2,
                    &mut expected_site1,
                    &mut expected_site2,
                ] {
                    x.clear();
                }
                for node_index in self.graph.node_indices() {
                    let node: &NodeDatum = &self.graph[node_index];
                    let base = &node.hap[..];
                    let pos = node.pos;
                    match (pos as i32) - (idx as i32) {
                        0 => {
                            expected_site1.insert(base);
                        }
                        1 => {
                            expected_site2.insert(base);
                        }
                        _ => {}
                    }
                }
                for (from_id, to_id, _count) in edges {
                    let from = &self.graph[NodeIndex::new(*from_id as usize)];
                    let to = &self.graph[NodeIndex::new(*to_id as usize)];
                    site1.insert(&from.hap[..]);
                    site2.insert(&to.hap[..]);
                    dlinks.entry(*from_id).or_default().insert(*to_id);
                }
                if (&site1, &site2) == (&expected_site1, &expected_site2) {
                    if dlinks.values().any(|x| x.len() > 1) {
                        SegmentationClass::Ten
                    } else {
                        SegmentationClass::Two
                    }
                } else {
                    SegmentationClass::Unassigned
                }
            } else {
                SegmentationClass::Unassigned
            };
            self.dnhap.insert(idx, nhap);
        }
        if self.settings.pivot_index > 0 {
            if let Some(height) = self
                .dnhap
                .get_mut(&((self.settings.pivot_index - 1) as u32))
            {
                if *height == SegmentationClass::Two {
                    *height = SegmentationClass::Ten;
                }
            }
        }
        Ok(())
    }

    /// Computes the minimum edge support for given read counts.
    /// Higher coverage samples need slightly higher thresholds.
    #[must_use]
    pub fn edge_support_threshold<T: TryInto<usize> + Copy>(num_reads: &[T]) -> u32 {
        let min_count = num_reads
            .iter()
            .map(|x| {
                (*x).try_into()
                    .unwrap_or_else(|_| panic!("Failed to convert"))
            })
            .min()
            .unwrap_or(0);
        let total_min = num_reads
            .iter()
            .map(|x| {
                (*x).try_into()
                    .unwrap_or_else(|_| panic!("Failed to convert"))
            })
            .filter(|x| *x != min_count)
            .min()
            .unwrap_or(0);
        if total_min > 10 {
            std::cmp::min(5, std::cmp::max(2, total_min / 25)) as u32
        } else {
            u32::from(total_min > 5)
        }
    }

    /// Retrieve haplotypes at position, converted to owned representations.
    /// For views alone, use `Graph::get_hap_by_pos`.
    #[must_use]
    pub fn get_owned_haps_by_pos(&self, pos: u32) -> Vec<VString> {
        self.get_hap_by_pos(pos)
            .map(VString::from)
            .collect::<Vec<_>>()
    }

    /// Assemble region in pos1..=pos2
    ///     pos1: first position used.
    ///     pos2: last position used.
    ///     `allow_x`: bool : if true, missing candidates will be output with x's appended.
    /// Returns:
    ///     bool: assembly success
    ///     `pos1_haps`: `Vec<VString>` - assembled haps.
    ///     where dnext and dbefore has pairs of connected fingerprint substrings.
    ///     dnext, dbefore: `BTreeMap<VString, BTreeSet<VString>>`.
    ///
    /// # Errors
    /// 1. `anyhow::anyhow` - missing next position.
    /// 2. `anyhow::anyhow` - merge two positions fail
    /// # Panics
    pub fn subregion_assembly(
        &mut self,
        pos1: u32,
        pos2: u32,
        allow_x: bool,
    ) -> Result<SubregionResult, DError> {
        let mut success = true;
        let mut curr_pos1 = pos1;
        let mut pos1_haps = self.get_owned_haps_by_pos(pos1);
        log::trace!("[subregion_assembly] Initial pos1_haps: {pos1_haps:?} for {pos1}..={pos2}. Pos edge map: {:?}", self.formatted_edges());
        if pos1_haps.is_empty() {
            return Err(Box::new(GraphError {
                msg: format!("pos1 haps is empty at {pos1}..={pos2}. Allow x: {allow_x}"),
            }));
        }
        assert!(!pos1_haps.is_empty());
        let mut dnext = BTreeMap::new();
        let mut dbefore = BTreeMap::new();
        let mut iternum = 1usize;
        while curr_pos1 < pos2 {
            let next_pos = self.get_next_pos(curr_pos1).ok_or_else(|| {
                anyhow::anyhow!(
                    "Missing next position: {curr_pos1} query, initial pos {pos1} and pos2 {pos2}"
                )
            })?;
            let next_haps = self.get_owned_haps_by_pos(next_pos);
            log::trace!("[subregion_assembly@{iternum}] {curr_pos1} and {pos2} assembly for initial pos1 {pos1}. Current pos1_haps: {pos1_haps:?}. And {next_haps:?} at {next_pos}. Edges at this point, before use: {:?}", self.formatted_edges());
            if ![&pos1_haps, &next_haps].iter().all(|x| !x.is_empty()) {
                return Err(Box::new(GraphError {
                    msg: format!("pos1 haps or next haps are empty. {pos1_haps:?}, {next_haps:?}"),
                }));
            }
            let mut subregion_haps_assembled = BTreeSet::new();
            if pos1_haps.len() == 1 || next_haps.len() == 1 {
                for (hap1, hap2) in iproduct!(pos1_haps.iter(), next_haps.iter()) {
                    let new_hap = {
                        let mut x = VString::from(hap1);
                        x.extend_from_slice(hap2);
                        x
                    };
                    log::trace!("[subregion_assembly@{iternum}] Merging hap1 and hap2 {hap1}/{hap2} because there was only one of each. New hap: {new_hap}. next_pos: {next_pos}. Current pos: {curr_pos1}");
                    subregion_haps_assembled.insert(new_hap);
                }
                dnext.clear();
                dbefore.clear();
            } else {
                log::trace!("[subregion_assembly@{iternum}] Complex dnext/dbefore");
                let new_nodes = [(pos1, &pos1_haps), (next_pos, &next_haps)]
                    .into_iter()
                    .map(|(k, value)| (k, value.iter().map(|x| x.vstr()).collect::<BTreeSet<_>>()))
                    .collect::<BTreeMap<_, _>>();
                let (sub_hap, dnext_new, dbefore_new) = self.merge_two_pos(&new_nodes)?;
                dnext = dnext_new
                    .into_iter()
                    .map(|(k, v)| {
                        (
                            VString::from(k),
                            v.into_iter().map(VString::from).collect::<BTreeSet<_>>(),
                        )
                    })
                    .collect::<BTreeMap<_, _>>();
                dbefore = dbefore_new
                    .into_iter()
                    .map(|(k, v)| {
                        (
                            VString::from(k),
                            v.into_iter().map(VString::from).collect::<BTreeSet<_>>(),
                        )
                    })
                    .collect::<BTreeMap<_, _>>();
                let thres = Self::get_len_threshold(pos1_haps[0].len(), next_haps[0].len());
                log::trace!("[subregion_assembly@{iternum}] from new nodes {new_nodes:?} we get dnext: {dnext:?}. dbefore: {dbefore:?} after merging two positions. Length threshold is {thres}");

                for (hap, reads) in sub_hap.iter().filter(|(_hap, reads)| reads.len() >= thres) {
                    log::trace!(
                        "[subregion_assembly@{iternum}] Adding in hap {hap:?} from merge_two_pos because {} >= {thres}",
                        reads.len()
                    );
                    subregion_haps_assembled.insert(hap.clone());
                }
                // BTreeMap<VString, Vec<&'a ReadAlignmentId>>,
            }
            let (mut left, mut right) =
                Self::get_missing(&subregion_haps_assembled, &pos1_haps, &next_haps);
            log::trace!("[subregion_assembly@{iternum}] added in new subregion_haps_assembled: {subregion_haps_assembled:?}. Missing {left:?}/{right:?}");
            if !left.is_empty() || !right.is_empty() {
                log::trace!("[subregion_assembly] allow_x is {allow_x}");
                if !allow_x {
                    log::trace!(
                        "[subregion_assembly] No allow x; returning. pos1 haps: {pos1_haps:?} with dnext/dbefore {dnext:?}/{dbefore:?} for range {pos1}..={pos2}. Edges: {:?}", self.formatted_edges(),
                    );
                    success = false;
                    return Ok((success, pos1_haps, dnext, dbefore));
                }
                let hap_len1 = pos1_haps[0].len();
                let hap_len2 = next_haps[0].len();
                if std::cmp::min(hap_len1, hap_len2) >= 3
                    && matches!(
                        self.dnhap
                            .get(&(next_pos - 1))
                            .map(SegmentationClass::is_assigned),
                        Some(true)
                    )
                    && self
                        .edge_info
                        .get(next_pos as usize - 1)
                        .and_then(|x| x.iter().copied().max())
                        .unwrap_or(0)
                        >= 2
                {
                    let mut missing = Self::rescue_missing(&left, &right, &dnext, &dbefore);
                    log::trace!("[subregion_assembly] missing rescued: {missing:?} for {left:?} and {right:?}");
                    subregion_haps_assembled.append(&mut missing);
                    (left, right) =
                        Self::get_missing(&subregion_haps_assembled, &pos1_haps, &next_haps);
                    log::trace!(
                        "[subregion_assembly] remaining missing after rescue_missing. left: {left:?}. right: {right:?}"
                    );
                } else {
                    log::trace!("[subregion_assembly] Could not rescue for left and right {left:?} and right {right:?}");
                }

                for missing in &right {
                    let mut hap = vec![b'x'; hap_len1];
                    hap.extend_from_slice(&missing[..]);
                    subregion_haps_assembled.insert(VString::from(hap));
                }
                let x_missing = vec![b'x'; hap_len2];
                for missing in &left {
                    let mut hap = (*missing).clone();
                    hap.extend_from_slice(&x_missing);
                    subregion_haps_assembled.insert(hap);
                }
            }
            pos1_haps = subregion_haps_assembled
                .into_iter()
                .collect::<Vec<VString>>();
            curr_pos1 = next_pos;
            iternum += 1;
        } // while curr_pos1 < pos2
        log::trace!("[subregion_assembly] after subregion assembly for {pos1}..={pos2}, pos_edge_map is {:?}. dnext and dbefore are {dnext:?} and {dbefore:?}. Formatted: {:?}", self.pos_edge_map, self.formatted_edges());
        Ok((success, pos1_haps, dnext, dbefore))
    }

    /// Compute read support count threshold for haplotypes of different lengths.
    /// x and y correspond to left/right hand fingerprint substrings at a given position.
    #[must_use]
    fn get_len_threshold(x: usize, y: usize) -> usize {
        let maxlen = std::cmp::max(x, y);
        let minlen = std::cmp::min(x, y);
        if minlen > 2 || (minlen == 2 && maxlen >= 10) {
            1
        } else {
            2
        }
    }

    /// Find the best matches for nodes given a query fingerprint.
    ///     Parameters:
    ///         `new_nodes` (BTreeMap): two positions and their associated partial haplotypes
    ///         pos1 (int): positions of interest
    ///         hap (str): full fingerprint
    ///     Returns:
    ///         (hap1, match)
    ///         hap1: corresponding segment in the read
    ///         match: Option<(`max_match`, `best_match`)>
    ///         `best_match`: list of best matches
    ///         `max_match`: length of the best matches
    pub fn get_matching_hap<'a, 'b, C, IntoVstr: std::convert::Into<VStr<'a>>>(
        nodes: &'a BTreeMap<u32, C>,
        pos1: u32,
        hap: VStr<'b>,
    ) -> Result<(VStr<'b>, Option<MatchingHapSet<'a>>), DError>
    where
        &'a C: std::iter::IntoIterator<Item = IntoVstr>,
    {
        let candidates = nodes
            .get(&pos1)
            .expect("Missing position")
            .into_iter()
            .map(std::convert::Into::into)
            .collect::<Vec<_>>();
        let pos1 = pos1 as usize;
        let pos2 = candidates[0].len();
        if pos1 + pos2 > hap.len() {
            return Err(Box::new(GraphError {
                msg: format!("{pos1} and {pos2} for hap {hap} is out of bounds"),
            }));
        }
        // hap1 = hap[pos1 : (pos1 + pos2)]
        let hap1 = VStr::from(&hap[pos1..(pos1 + pos2)]);
        log::trace!(
            "query hap {hap1} into candidates {candidates:?} with pos2 {pos2} and pos1 {pos1}"
        );

        let mut matches: BTreeMap<_, Vec<_>> = BTreeMap::new();
        for cand in candidates {
            let cmp = HapCompare::from_haps(&cand[..], hap1)?;
            if cmp.mismatches > 0 || cmp.matches <= 0 {
                continue;
            }
            matches.entry(cmp.matches).or_default().push(cand);
        }

        let best_match = matches
            .into_iter()
            .max_by_key(|x| x.0)
            .map(|(key, value)| (key, value.clone()));
        Ok((hap1, best_match))
    }
} // Graph

#[cfg(test)]
mod tests {
    // Corresponds to tests/test_haplotype_assembler.py:test_initialize_graph
    mod init_graph {
        use crate::assembly::node_datum::NodeDatum;
        use crate::detail::util::DResult;
        use crate::io::json::{ReadAlignmentId, ReadFingerprintMap};
        #[test]
        fn test_graph_constructor_ok() -> DResult {
            use crate::assembly::variant_graph::*;
            use itertools::Itertools;
            let mut read_inputs = [
                ("r1", "11x"),
                ("r2", "11x"),
                ("r3", "22x"),
                ("r4", "22x"),
                ("r5", "x12"),
                ("r6", "x22"),
                ("r7", "x2x"),
                ("r8", "x22"),
                ("r9", "x11"),
                ("r10", "x11"),
                ("r11", "x22"),
                ("r12", "x22"),
                ("r13", "x22"),
                ("r14", "x22"),
                ("r15", "x11"),
                ("r16", "x11"),
                ("r17", "x11"),
                ("r18", "x11"),
            ]
            .into_iter()
            .map(|(x, y)| (ReadAlignmentId::from_name(x), vstr::VString::from(y)))
            .collect::<ReadFingerprintMap>();
            let mut graph = Graph::try_new(read_inputs.clone(), None)?;
            graph.init()?;
            let expected_nodes = [(1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)];
            let expected_nodes = expected_nodes
                .into_iter()
                .map(|(value, position)| {
                    let value = value as u8 + b'0';
                    NodeDatum::from((value, position as usize))
                })
                .sorted()
                .collect::<Vec<_>>();
            let nodes = graph.node_iter().cloned().sorted().collect::<Vec<_>>();
            assert_eq!(nodes, expected_nodes);
            let edges = graph
                .graph
                .edge_references()
                .map(|edge| {
                    graph
                        .paraphase_format_edge(edge.id(), None)
                        .expect("Edge missing")
                })
                .sorted()
                .collect::<Vec<(String, String)>>();

            let expected_edges = [
                ("1-0", "1-1"),
                ("2-0", "2-1"),
                ("2-1", "2-2"),
                ("1-1", "1-2"),
            ]
            .into_iter()
            .map(|(x, y)| (String::from(x), String::from(y)))
            .sorted()
            .collect::<Vec<(String, String)>>();
            assert_eq!(edges, expected_edges);

            assert!(!graph.reads.contains_key(&ReadAlignmentId::from_name("r5")));

            // Now remove node and test read allowance.
            // r5 should be present now.
            assert!(read_inputs
                .remove(&ReadAlignmentId::from_name("r18"))
                .is_some());

            let mut graph = Graph::try_new(read_inputs.clone(), None)?;
            graph.init()?;

            let nodes = graph.node_iter().cloned().sorted().collect::<Vec<_>>();
            assert_eq!(nodes, expected_nodes);

            let edges = graph
                .graph
                .edge_references()
                .map(|edge| {
                    graph
                        .paraphase_format_edge(edge.id(), None)
                        .expect("Nodes missing from graph.")
                })
                .sorted()
                .collect::<Vec<(String, String)>>();
            let expected_edges = [
                ("1-0", "1-1"),
                ("2-0", "2-1"),
                ("1-1", "2-2"),
                ("2-1", "2-2"),
                ("1-1", "1-2"),
            ]
            .into_iter()
            .map(|(x, y)| (String::from(x), String::from(y)))
            .sorted()
            .collect::<Vec<(String, String)>>();
            assert_eq!(edges, expected_edges);
            assert!(graph.reads.contains_key(&ReadAlignmentId::from_name("r5")));
            assert!(!graph.pos_edge_map.is_empty());
            {
                let map = &graph.pos_edge_map;
                log::debug!("Map: {map:?}");
                let format_edge = |edge: &WeightedEdge| -> (String, String, u32) {
                    let source = NodeIndex::new(edge.0 as usize);
                    let target = NodeIndex::new(edge.1 as usize);
                    let res = graph
                        .paraphase_format_edge(
                            graph
                                .find_edge(source, target)
                                .expect("Missing edge from graph"),
                            None,
                        )
                        .expect("Failed to format edge pair");
                    (res.0, res.1, edge.2)
                };
                assert_eq!(map.len(), 2);
                assert_eq!(map[&0].len(), 2);
                assert_eq!(map[&1].len(), 3);
                assert_eq!(
                    &map[&0].iter().map(format_edge).collect::<Vec<_>>()[..],
                    &[
                        (String::from("1-0"), String::from("1-1"), 2),
                        (String::from("2-0"), String::from("2-1"), 2)
                    ]
                );
            }
            Ok(())
        }
        #[test]
        fn summarize_edges_ok() -> DResult {
            use crate::assembly::variant_graph::SegmentationClass;
            use crate::assembly::variant_graph::SegmentationClass::*;
            use std::collections::BTreeMap;
            let read_inputs = [("r1", "11"), ("r2", "22")]
                .into_iter()
                .map(|(x, y)| (ReadAlignmentId::from_name(x), vstr::VString::from(y)))
                .collect::<ReadFingerprintMap>();
            let mut graph = crate::assembly::variant_graph::Graph::try_new(read_inputs, None)?;
            for node in [
                (b'1', 0), // 0
                (b'2', 0), // 1
                (b'1', 1), // 2
                (b'2', 1), // 3
                (b'1', 2), // 4
                (b'2', 2), // 5
                (b'1', 3), // 6
                (b'2', 3), // 7
                (b'1', 4), // 8
                (b'2', 4), // 9
            ]
            .into_iter()
            .map(|(chr, pos)| NodeDatum::from((chr, pos as usize)))
            {
                let (_id, was_new) = graph.fully_add_node(node);
                assert!(was_new);
            }
            assert_eq!(graph.total_node_count, 10);
            assert_eq!(graph.node_id_map.len(), 10);
            let mut edges: BTreeMap<usize, Vec<(u32, u32, u32)>> = BTreeMap::new();
            edges.insert(0, vec![(0, 2, 2), (1, 3, 3)]);
            edges.insert(1, vec![(2, 5, 2), (3, 5, 6), (2, 4, 5)]);
            edges.insert(2, vec![(4, 7, 2), (5, 7, 6), (4, 6, 5)]);
            edges.insert(3, vec![(6, 9, 2), (7, 9, 6), (6, 8, 5)]);
            /*
            let edges = vec![
                vec![(0, 2, 2), (1, 3, 3)],
                vec![(2, 5, 2), (3, 5, 6), (2, 4, 5)],
                vec![(4, 7, 2), (5, 7, 6), (4, 6, 5)],
                vec![(6, 9, 2), (7, 9, 6), (6, 8, 5)], /* [("1-3", "2-4", 2), ("2-3", "2-4", 6), ("1-3", "1-4", 5)], */
            ];
            */
            for (_idx, edge_set) in &edges {
                for (from, to, _count) in edge_set {
                    //for (from, to, _count) in edges.iter().flatten().copied() {
                    graph.add_edge((*from).into(), (*to).into(), vec![]);
                }
            }
            graph.pos_edge_map = edges;
            graph.summarize_edges()?;
            let expected_dnhap = [(0, Two), (1, Ten), (2, Ten), (3, Ten)]
                .into_iter()
                .collect::<BTreeMap<u32, SegmentationClass>>();
            log::debug!("Found {:?} dnhap, expected {expected_dnhap:?}", graph.dnhap);
            assert_eq!(expected_dnhap, graph.dnhap);
            Ok(())
        }
    } // init_graph
}
